=pod

=head1 NAME

PartCat - Electronic Components Cataloger and Organizer

=head1 SUMMARY

A client for the L<PartCat server|https://github.com/innoveworkshop/partcat-server>.
This will enable you to manage your entire library of electronic components.

=head1 REQUIREMENTS

To run this software you'll require all the libraries that are listed in the
C<cpanfile> and also L<Tklib|https://www.tcl.tk/software/tklib/>.

=head1 SETUP

Just run C<make>.

=head1 TESTING

To make sure everything is perfect for deployment you can run C<make test>,
which will run all the unit tests to make sure that you have a working system.

=head1 AUTHOR

Nathan Campos <nathan@innoveworkhsop.com>

=head1 COPYRIGHT

Copyright (c) 2019- Innove Workshop Company.

=cut
